### PR TITLE
Adding a check your progress in Hacktoberfest (Lets see if this shows up now)

### PR DESCRIPTION
**Pull request by JamesSingleton**
Lets see if this shows up now haha. Looks like it isn't showing up... oh well.

### CODE REVIEW

**Comment by sreetamdas** [comment]
Hmm. I can see that there might be an error with the way that you've set up your git email, says you're using `DrSarge`, maybe that's causing this?

**Comment by JamesSingleton** [comment]
DrSarge was my old one, but the other 2 repos show that as well. I wonder if it is because everything was done under  (master | rebase) because I had to rebase everything. That would suck...

**Comment by JamesSingleton** [comment]
@sreetamdas ,

I reached out to GitHub and apparently this is a known issue they are working on.

**Comment by sreetamdas** [comment]
is there a link that I can check out for this?

**Comment by JamesSingleton** [comment]
@sreetamdas,

Not that I am aware of, I emailed them via their contact us page. However, it should be resolved, or it is for me now anyways.

**Comment by sreetamdas** [comment]
Ah. That's great!

**Pull request merged**
