### PR TITLE
Adding JamesSingleton as contributor to Hacktoberfest

### PR DESCRIPTION
**Pull request by JamesSingleton**
Completed the instructions.

### CODE REVIEW

**Comment by JamesSingleton** [comment]
Resolved the conflicts.

**Comment by JamesSingleton** [comment]
What is interesting @sreetamdas, this doesn't show up as a pull request for https://github.com/sreetamdas/newbie-hacktoberfest/issues/1 or under my pull requests... weird

**Comment by sreetamdas** [comment]
@JamesSingleton you can see that the issue gets a comment saying that it has been mentioned here just now. 
The issue only gets mentioned when it is explicitly mentioned, like: #1 

screenshot from 2017-10-22 00-20-36

**Comment by JamesSingleton** [comment]
@sreetamdas,

I was just saying this it doesn't show up here:

image

And then if I search for merged pull requests, it doesn't show, I wondering if it is behind for some reason?

**Comment by sreetamdas** [comment]
oh, that.
Its been pretty much real time for me.
weird indeed; you can try sending another PR

**Pull request merged**
